# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-QEEYF61RPX'

menu:
- {name: 'About Me', folder: 'pages', file: 'about.html'}
- {name: 'Education', folder: 'pages', file: 'education.html'}
- {name: 'Projects', folder: 'pages', file: 'projects.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}


#- {name: 'Documentation', folder: 'pages', file: 'documentation.html'}
#- {name: 'About', folder: 'pages', file: 'about.html'}
# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/vaydingul'}
- {icon: 'instagram', link: 'https://instagram.com/vaydingul'}
- {icon: 'github', link: 'https://github.com/vaydingul'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/volkan-ayding%C3%BCl-5a516117a/'}
- {icon: 'envelope', link: 'mailto:volkanaydingul@gmail.com'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
